/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/userInfo": {
    /**
     * Gets all User Info
     * @description Gets all Users and their corresponding details
     */
    get: {
      responses: {
        /** @description A JSON array of users and corresponding details */
        200: {
          content: {
            "application/json": {
                /** @example 12345 */
                userId?: number;
                /** @example sample@gmail.com */
                email?: string;
                /** @example Mike Jones */
                username?: string;
                /** @example I like to bike */
                bio?: string;
              }[];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: never;
        };
      };
    };
  };
  "/user": {
    /**
     * Create a new User
     * @description Create a new User
     */
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** @example Mike123 */
            email?: string;
            /** @example password123 */
            password?: string;
          };
        };
      };
      responses: {
        /** @description Successfully created User */
        201: {
          content: never;
        };
        /** @description Invalid Request */
        400: {
          content: never;
        };
        /** @description Internal Server Error */
        500: {
          content: never;
        };
      };
    };
    /**
     * Delete a User
     * @description Remove a User and their data from our records
     */
    delete: {
      requestBody: {
        content: {
          "application/json": {
            /** @example 12345 */
            userId?: string;
          };
        };
      };
      responses: {
        /** @description Successfully deleted User and Details */
        200: {
          content: never;
        };
        /** @description Invalid Request */
        400: {
          content: never;
        };
        /** @description Internal Server Error */
        500: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
